### ISSUE TITLE
Cyanogen Mod is here

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_huawei_hi6210sft#1]
Cyanogen Mod is here, let's start debugging.

![screenshot_2016-08-04-22-25-07](https://cloud.githubusercontent.com/assets/6603252/17432896/ee3564d8-5b01-11e6-829b-cb084059b02a.png)

**Comment by kopr97** [comment]
Nice good job :)

**Comment by hak86** [comment]
I'm uploading a beta image will be available via "original android" developments section on xda ;)

**Comment by kopr97** [comment]
Thanks :)

**Comment by carlis97** [comment]
Hello, what is not working in this ROM ?

**Comment by hak86** [comment]
audio, bt, wifi, ril, camera, nfc
works: gps, already fixed
I'm working to make it more stable

**Comment by carlis97** [comment]
Okay, I trust you can take care of this nice project

**Comment by hak86** [comment]
sure i will do the best

**Comment by Panchovix** [comment]
Nice work! i sent this post to hackslash to see if he can do something with Honor 4x/4c (kirin 620), since p8 lite system.img are too much to these phones :(

**Comment by hak86** [comment]
mention me as "haky 86" on xda  if work on your device, i got some problems with upload, will try again

**Comment by mefetran** [comment]
What about phone call. Does sim-card will work?

**Comment by Perenty** [comment]
@mefetran RIL is not working. That means, it is'nt working yet.

**Comment by VenityZ** [comment]
@mefetran no 
@hak86 https://github.com/mt7-dev/aosp_frameworks_opt_telephony
https://github.com/XePeleato/Hi6XXX_Telephony
Maybe it works on cm 12.1 too

**Comment by mefetran** [comment]
@hak86, I mean, that it WILL work or no? I traded, that it's so hard to fix.

**Comment by mefetran** [comment]
Read*

**Comment by kopr97** [comment]
@hak86 and what about uploading ???

**Comment by hak86** [comment]
is finish, i am preparing xda topic, since is a beta, don't pretend a fully build will be solved soon as well :)

**Comment by hak86** [comment]
http://forum.xda-developers.com/p8lite/orig-development/rom-cyanogen-mod-12-0-huawei-p8-lite-t3433523

**Comment by kopr97** [comment]
download not work

**Comment by hak86** [comment]
just a moment

**Comment by kopr97** [comment]
now works thanks :)

**Comment by carlis97** [comment]
I test it, and are amazing rom, i wish in the future, works wifi and RIL services
Good Job @hak86 you're amazing
