### ISSUE TITLE
Fixed Features on CM-12.1

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_huawei_hi6210sft#2]
- [x] Audio (in progress)
- [x] Bluetooth.
- [x] Bluetooth Shared.
- [x] GPS.
- [x] NFC (almost fixed).
- [x] Wifi.

# as always no ETA

**Comment by carlis97** [comment]
Where test it, you will upload ROM? Thanks Hak86 :D

**Comment by hak86** [comment]
once got NFC work, then will release a flexible build, at least I'm doing the possible to get other features works, like audio and ril.

**Comment by carlis97** [comment]
Okey Hak86, we waiting for The new features, thanks for all ^^

**Comment by HaDy92** [comment]
Any news on RIL

**Comment by hak86** [comment]
not work on cm-12.1, will switch to newer version soon.
