### ISSUE TITLE
Ramdisk Reduced

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_huawei_hi6210sft#5]
Hi devs

I reduce the quantity of files used by ramdisk.img from 38 files to just 7 and might will be reduced to 5 or 4 files only, in that way will help to see which proprietary  files are used by system/bin and system/sbin to get all features works, I will push the commit once reduces as well, so why should i see all that useless files, see nexus 5 (hamerhead)
![screenshot_2016-03-25-10-23-13](https://cloud.githubusercontent.com/assets/6603252/14041753/33650a50-f274-11e5-8389-19ce201a4f7c.png)
) sample it's work only with 4 or 5 .rc  :+1:

**Comment by muhammadfahadbaig** [comment]
Sorry if it's off topic. Just wanted to ask did you used Huawei sources or HiKey sources to compile the kernel?

**Comment by hak86** [comment]
yes me and Eduardo, use same stock kernel, the hikey use hi6220 if not wrong, but yesterday one of 96boards devs, told me kirin 620 is officially supported by google.
http://emui.huawei.com/en/plugin.php?id=hwdownload&mod=detail&mid=103

**Comment by muhammadfahadbaig** [comment]
Sis you extracted the kernel from boot.IMG or compiled it from source? I compiled one yesterday and it was successful but the resultant image size was 13 MB compared to 19 MB in boot.img

**Comment by muhammadfahadbaig** [comment]
It's sir. Sorry about that. My keyboard changed it to sis. ;P

**Comment by hak86** [comment]
well, the default sile of zImage is around 19mb, my compiled one is 20.8, to repack it, use this tool 
https://github.com/xiaolu/mkbootimg_tools, forget the rest of tools for repacking, the linked one is the best.

**Comment by muhammadfahadbaig** [comment]
So you compiled the kernel from Huawei Sources from scratch.

**Comment by hak86** [comment]
at the moment from kernel source, not via make -j4 bootimg, since we don't know the correct configuration, i try to rename some configurations from lettuce device tree to compile kernel via make -j4 bootimg but didn't work, so prebuilt zImage is the best way.

**Comment by muhammadfahadbaig** [comment]
I compiled the zImage from Huawei Sources. It was successful but the resultant zImage is 13 MB...don't know what I'm missing...

**Comment by hak86** [comment]
hmm, use Eduardo's kernel one ;)

**Comment by XePeleato** [comment]
If it doesn't work, try a `make clean` first

**Comment by muhammadfahadbaig** [comment]
The problem is here. The arm config builds the image successfully. However the arm64 is causing problems. The build stops at error... Make init/mounts.o failed . Will examine the makefile again. I did make clean && make mrproper.

**Comment by hak86** [comment]
i guess you are not using the correct gcc

**Comment by muhammadfahadbaig** [comment]
I am using aarch64-linux-android-4.9 from Google ndk.

**Comment by XePeleato** [comment]
I included a script to build the kernel with the toolchain that I included there

**Comment by olrak2** [comment]
@muhammadfahadbaig look at this, some nightwork :smiley: 
https://github.com/olrak2/make_boot_image_hi6210sft

**Comment by muhammadfahadbaig** [comment]
The problem is not with boot.IMG but with the Image file I get after compiling kernel from Huawei Sources. The Image size is only 13 MB compared to actual 19 MB. I am now building from your provided kernel sources and @xepleato toolchains. It's building but with a hell lot of make errors.

**Comment by olrak2** [comment]
that's Huawei Developers fault :smile: , as long it's build it's good.

**Comment by muhammadfahadbaig** [comment]
@olrak2 great work!!! I was able to compile the Image successfully.
