### ISSUE TITLE
CM-12.1 Is Booting

### ISSUE THREAD

**Issue by hak86** [hak86/android_device_huawei_hi6210sft#7]
The rom is booting, but stuck on logo, I'm gonna to add init.superuser.rc and init.cm.rc to complete boot ;)
![img_20160408_003507](https://cloud.githubusercontent.com/assets/6603252/14369053/434c9862-fd22-11e5-8ad2-7af9ae0975e0.jpg)

**Comment by muhammadfahadbaig** [comment]
Congrats!! I'm still stuck on Android Runtime crashing. :(

**Comment by hak86** [comment]
My issue it's the stupid ramdisk + some vendors are not putted in the correct path :)

**Comment by muhammadfahadbaig** [comment]
What about the symlinks in /data/ . For all the ramdisk files, it is crucial those symlinks are not destroyed.

**Comment by darklion1496** [comment]
Hello, have you finish it? You are god

**Comment by hak86** [comment]
my problem is ramdisk, the tree is ready, so i will try to fix it before upload :3

**Comment by darklion1496** [comment]
Thank you for this ROM, i belive in you work and belive  it was possible.

**Comment by darklion1496** [comment]
Hello, what's new?

**Comment by XePeleato** [comment]
He said he would upload it as soon as he finishes it

**Comment by hak86** [comment]
still don't understand why ramdisk is stuck on cyanogen mod animation boot. i manage to formate my computer and back to ubuntu 14.04 since the best version to build android.
perhaps a selinux issue.

**Comment by XePeleato** [comment]
Perhaps uploading the logs could be useful

**Comment by muhammadfahadbaig** [comment]
SELinux must be set to permissive. Also try using Kernel sources instead of prebuilt kernel.

**Comment by hak86** [comment]
sure, I will do after finish downloading cm tree. for adb, isn't working, so I will try with one of this configuration to enable ADB.

**Comment by olrak2** [comment]
Don't know if it needed? But don't we need to rewrite the ramdisk files to a much easier layout?

So we can dump the stock ones and only use the ones that are rewritten.

**Comment by hak86** [comment]
yes olrak, i use the stock one without modification except the file init.envir.rc which i use the default one came with cyanogen mod tree.

**Comment by XePeleato** [comment]
I got logcat working on my CM12-1 build, however I stopped it because of some hwcomposer error, I'll upload it, maybe that helps.

**Comment by darklion1496** [comment]
Hello Hak86 the ROM android 6.0 for the huawei ALE-L21 has released, i think this oficial ROM can solve the problems

http://consumer.huawei.com/es/support/downloads/detail/index.htm?id=78426&key4=ALE-L21

**Comment by hak86** [comment]
which problem?
i am doing a build right now, and compile it without java (a problem on environment)

**Comment by darklion1496** [comment]
Ohhh, make it possible, good luck, thank you so much for do this. :) ¿Can you upload the rom today? To test

**Comment by FelipeBR28** [comment]
Hi, sorry for posting, anybody knows why when I try to unlock bootloader I get "FAILED (status malformed (1 bytes))"? I want to flash TWRP 3.0 but I always get that error. How to fix?

**Comment by hak86** [comment]
@FelipeBR28 did you unlock the bootloader?

**Comment by FelipeBR28** [comment]
@hak86 the error I get it when I try to unlock the bootloader

**Comment by darklion1496** [comment]
@FelipeBR28 can you try this automatic unlocker

http://www.htcmania.com/showthread.php?t=1021968

**Comment by FelipeBR28** [comment]
@darklion1496 I even tried, from automatic, to manual but nothing works...

**Comment by darklion1496** [comment]
Try to change the ROM to a old versión or change to the oficial 6.0, maybe solv the problems

**Comment by FelipeBR28** [comment]
@darklion1496 I'm on the official one, and I can't change it because I don't have the bootloader unlocked, I thought about it.

**Comment by muhammadfahadbaig** [comment]
Please post the output of 
fastboot getvar all

**Comment by VenityZ** [comment]
Are you sure that you use the Unlock Code that Huawei send you?

**Comment by FelipeBR28** [comment]
@muhammadfahadbaig 
Microsoft Windows [Versión 10.0.10586]
(c) 2015 Microsoft Corporation. Todos los derechos reservados.

C:\Program Files (x86)\Minimal ADB and Fastboot>fastboot oem unlock 860938030034300
...
FAILED (status malformed (1 bytes))
finished. total time: 0.233s

C:\Program Files (x86)\Minimal ADB and Fastboot>fastboot getvar all
getvar:all FAILED (remote: Command not allowed)
finished. total time: 0.005s

C:\Program Files (x86)\Minimal ADB and Fastboot>

**Comment by FelipeBR28** [comment]
@VenityZ completely sure, they sent me last week

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 Hmm... the issue is not with the unlock code. Check the USB cable. Sometimes a faulty USB cable can't send data to the fastboot resulting in 'Status Malformed" error. (It's evident that the the first byte wasn't sent which could be due to the faulty cable). Use original Huawei Cable or any other USB cable.

**Comment by FelipeBR28** [comment]
@muhammadfahadbaig I'm using the original one, but I'll try with another... Thanks for the help!

**Comment by FelipeBR28** [comment]
Still the same, I tried with the original one and four different more and nothing. Maybe my phone isn't able to do it :(

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 There is definitely something wrong with your bootloader. What's your Android version?

**Comment by FelipeBR28** [comment]
@muhammadfahadbaig is the official release for Spain of MM B550, I'd like to downgrade to Lollipop but as I don't have it unlocked, I can't, if the problem is because of the version, is any other way to downgrade?

**Comment by XePeleato** [comment]
@FelipeBR28 I unlocked mine and flashed over a hundred test roms without an issue, I am using a GNU/Linux distribution. Maybe it's worth trying  it.

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 Unfortunately there is no easy way to downgrade. There is one method but that requires fastboot (which in your case is broken). You can however try to reinstall the complete MM ROM. 
You may also extract RECOVERY.img from B550 using Huawei Update Extractor and flash it using fastboot flash recovery recovery.img (this is just to knoe what fastboot throws at you when you try to flash signed images).
If this doesn't works, I suppose the USB connectors to the board are faulty. So you may send it for a repair.

**Comment by VenityZ** [comment]
+muhammadfahadbaig There is a easy way to Downgrade 😊 with the Downgrade pakage B300 works always fine for me. And +FelipeBR28 http://huaweip8lite.blogspot.de/2016/03/bootloader-huawei-p8-lite-14-huawei.html?m=1 translate if you don't understand russian

**Comment by VenityZ** [comment]
oh wow + instead @ 😑

**Comment by muhammadfahadbaig** [comment]
@VenityZ Well that's great then!

**Comment by VenityZ** [comment]
Here i the downgrade pakage for it only worked with B170 http://consumer.huawei.com/pl/mobile-phones/support/downloads/detail/p8-lite-pl.htm?id=70279#anchor

**Comment by FelipeBR28** [comment]
Well, I downgraded by B300 to B170 but still I can't unlock it. It's impossible, but I won't send it for repair, I've done it like 4 times. I won't do anything because is impossible, thanks for all the help still!!!!

**Comment by XePeleato** [comment]
@FelipeBR28 No it's not, Just install a Linux based distro and try from there. Are you using an ALE-L21?

**Comment by FelipeBR28** [comment]
@XePeleato I'll install Ubuntu is enough? But I don't know the commands to use on Linux. Yes I do, from factory.

**Comment by XePeleato** [comment]
@FelipeBR28 Ubuntu should do, you just need to install fastboot and run it, you can even run Ubuntu from a Live CD I guess.

**Comment by FelipeBR28** [comment]
@XePeleato the commands are  the same as on Windows?

**Comment by XePeleato** [comment]
@FelipeBR28 The fastboot commands are the same, the other ones not really, however you won't need  to type a lot of commands

**Comment by VenityZ** [comment]
It's always God to have Ubuntu running on a virtual machine xP

**Comment by XePeleato** [comment]
Not a good idea, since Windows will load its fastboot driver.

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 Just run Ubuntu from a persistent USB install or Live CD. After that, follow this guide to set up ADB and Fastboot http://bernaerts.dyndns.org/linux/74-ubuntu/328-ubuntu-trusty-android-adb-fastboot-qtadb

**Comment by hak86** [comment]
to setup adb on ubuntu just run _sudo apt-get install android-tools-adb_, i am backing work on the project, due to frequenting java for android course. :)

**Comment by FelipeBR28** [comment]
Ok, It's installed, and ADB & fastboot too, thanks for giving me how to, but when I type fastboot oem unlock (code) it stucks in <waiting for device>, it's due to the drivers?

**Comment by XePeleato** [comment]
Type 'sudo'  before that, in order to run it as administrator.

**Comment by FelipeBR28** [comment]
Before...what?

**Comment by FelipeBR28** [comment]
FAILED (status malformed (1 bytes))
finished. total time: 0.232s
It's horrible.

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 What is your P8 Lite version and Build Version? Also, is your phone carrier locked (i.e. you bought it from a carrier rather than a retail one)

**Comment by FelipeBR28** [comment]
What do you mean with Version and Build Version? It's an ALE-L21 bought free

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 I asked if it's brought from a carrier because carriers usually lock Fastboot commands. Also can you try one more thing. Use Huawei Update Extractor (search on Google) to extract recovery.IMG from the stock Update.APP and then flash it through Fastboot _Fastboot flah recovery recovery.img_

**Comment by FelipeBR28** [comment]
![img_20160421_183207](https://cloud.githubusercontent.com/assets/17236000/14716989/a8883a92-07ef-11e6-8907-313aba1a0f8b.png)
OK, but, if the bootloader is locked, I would be able to do it?

**Comment by muhammadfahadbaig** [comment]
Yes you should be able to flash any stock image even if the bootloader is locked.

**Comment by FelipeBR28** [comment]
@muhammadfahadbaig I get "command not allowed"

**Comment by muhammadfahadbaig** [comment]
@FelipeBR28 that means your Fastboot is locked down pretty bad. Unfortunately, you might be never able to unlock your device.

**Comment by FelipeBR28** [comment]
@muhammadfahadbaig it's one of the new models, (changes some things in the box) and I think they're harder to unlock. If there's some other "strange" mode to unlock it, I'll try it, but with the normal ones I can't.

**Comment by muhammadfahadbaig** [comment]
@XePeleato @hak86 
So I decided to switch to using Kernel sources for building Cyanogenmod rather than using a prebuilt kernel. I've added these lines in BoardConfig.mk:
`TARGET_KERNEL_SOURCE := kernel/huawei/hi6210sft
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CONFIG := cyanogenmod_hi6210sft_defconfig
TARGET_USES_UNCOMPRESSED_KERNEL := true
BOARD_KERNEL_IMAGE_NAME := Image
#TARGET_PREBUILT_KERNEL := device/huawei/hi6210sft/kernel # Should be only used as fallback if sources aren't present`
However, I've no idea why the build is failing at:
`make: *** No rule to make target `/media/android/system/kernel/arch/arm/configs', needed by `/media/android/system/kernel/arch/arm/configs/hw_cm_hi6210sft_defconfig'.  Stop.`
It seems that the make is taking a wrong path `kernel/arch` because my sources are located at `kernel/huawei/hi6210sft`
Any help would be appreciated.

**Comment by hak86** [comment]
did you add audio effect from etc?

**Comment by muhammadfahadbaig** [comment]
@hak86 Thanks for replying back!
Yes, I have included audio_effects and audio_policy xml files from etc:
```
# Audio Configs
PRODUCT_COPY_FILES += \
			$(LOCAL_PATH)/audio/etc/audio_effects.xml:system/etc/audio_effects.xml \
			$(LOCAL_PATH)/audio/etc/audio_policy.xml:system/etc/audio_policy.xml 
```

**Comment by hak86** [comment]
I assume you have generic and alsa configuration in boardconfig, if not wrong to fix that error, check if have or not the libs for audio in system/libs, system/lib/hw same thing for 64 bit drivers.

**Comment by muhammadfahadbaig** [comment]
@hak86 thanks forget to set Generic Audio to false

**Comment by hak86** [comment]
I am doing a debuggable build, will report.

**Comment by hak86** [comment]
i think the missed overlay, some frameworks and probably binaries drivers are missed, see you on booted rom ;)
https://github.com/hak86/pastebin/blob/master/log7.txt

**Comment by muhammadfahadbaig** [comment]
@hak86 any logs to see? I see you're very active today (pushed many changes). :smiley:

**Comment by hak86** [comment]
yep, them rom was stuck before even cm animation run, i clean some binaries services used by ramdisk  which aren't available on stock firmware, update proprietary-files.txt to extract only .so drivers used by huawei and hisi, all etc configurations, now SHOULD boot as well, Ii think the tree is easier to read and more completed.

**Comment by muhammadfahadbaig** [comment]
Also stuck on Huawei logo. Device doesn't goes to cm animation. I'm also making a clean build again. Let's see...
May God be with you and may the CM run on P8 Lite. Amen!

**Comment by hak86** [comment]
our cpu is officially supported by Google, we just need to create a compatible device. what is the size of system.img you got?

**Comment by muhammadfahadbaig** [comment]
My system.img size was 726.6 MB (which will now increase as I have now included all Camera blobs incluing the OMX and Sony lens files)

**Comment by muhammadfahadbaig** [comment]
@hak86 what about the modemnvm1 , 2 and 3 partitions. Are they getting mounted at boot? (I didn't saw those partitions in fstab)

**Comment by ward0** [comment]
Do you have a xda topic of some kind pls?

**Comment by muhammadfahadbaig** [comment]
@hak86 I was wondering if we extract libs such as surfaceflinger, balong ril and GLES Mali directly from HiKey Board Android AOSP releases? As far as I think, those libraries could may be solve most of the problems (and maybe the surfaceflinger is compatible with mali userspace binaries and huawei gralloc).

**Comment by hak86** [comment]
that what  i'll do in next test, hikey tree + ramdisk of p8 lite.

**Comment by muhammadfahadbaig** [comment]
@hak86 That's great then. However here are the HiKey Vendor Blobs: https://github.com/muhammadfahadbaig/hikey_linaro_hi6210sft_vendor . These are for Android 6.0.1 (apparently all AOSP  releases for HiKey are 6.0 or newer)

**Comment by hak86** [comment]
testing them will not cost nothing, at least our cpu are pretty same both are hi6210sft, will fork them :D

**Comment by joker0013** [comment]
can you upload a testing version to test it ? 
i think i can help

**Comment by hak86** [comment]
mean device tree?

**Comment by hak86** [comment]
@muhammadfahadbaig hey bro I check the proprietary-files.txt there are only 2 drivers, i guess are requred to solve graphics issue on the boot
![screenshot from 2016-04-29 12-41-46](https://cloud.githubusercontent.com/assets/6603252/14914137/f6e3d11a-0e07-11e6-8672-bf3d90823bce.png)

**Comment by muhammadfahadbaig** [comment]
@hak86 Yes right about that (as far as I also think). These libGLES_mali.so should be compatible with AOSP and CM surfaceflinger. We're getting close :fireworks: 
And basically those are the only proprietary files HiKey uses. The rest are all generated during the build

**Comment by hak86** [comment]
yes for the moment we need a correct configurations for boot, another bugs can be fixed once ported as well ;)
